### Controller ###
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: conduit
  labels:
    app: controller
    conduit.io/control-plane-component: controller
  annotations:
    conduit.io/created-by: conduit/cli dev-126be6ff-siggy
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
  - name: http
    port: 8085
    targetPort: 8085

---
kind: Service
apiVersion: v1
metadata:
  name: proxy-api
  namespace: conduit
  labels:
    app: controller
    conduit.io/control-plane-component: controller
  annotations:
    conduit.io/created-by: conduit/cli dev-126be6ff-siggy
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
  - name: grpc
    port: 8086
    targetPort: 8086

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: controller
  namespace: conduit
  labels:
    app: controller
    conduit.io/control-plane-component: controller
  annotations:
    conduit.io/created-by: conduit/cli dev-126be6ff-siggy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
        conduit.io/control-plane-component: controller
      annotations:
        conduit.io/created-by: conduit/cli dev-126be6ff-siggy
    spec:
      serviceAccount: conduit-controller
      containers:
      - name: public-api
        ports:
        - name: http
          containerPort: 8085
        - name: admin-http
          containerPort: 9995
        image: gcr.io/runconduit/controller:dev-126be6ff-siggy
        imagePullPolicy: IfNotPresent
        args:
        - "public-api"
        - "-addr=:8085"
        - "-metrics-addr=:9995"
        - "-telemetry-addr=127.0.0.1:8087"
        - "-tap-addr=127.0.0.1:8088"
        - "-log-level=info"
      - name: destination
        ports:
        - name: grpc
          containerPort: 8089
        - name: admin-http
          containerPort: 9999
        image: gcr.io/runconduit/controller:dev-126be6ff-siggy
        imagePullPolicy: IfNotPresent
        args:
        - "destination"
        - "-addr=:8089"
        - "-metrics-addr=:9999"
        - "-log-level=info"
      - name: proxy-api
        ports:
        - name: grpc
          containerPort: 8086
        - name: admin-http
          containerPort: 9996
        image: gcr.io/runconduit/controller:dev-126be6ff-siggy
        imagePullPolicy: IfNotPresent
        args:
        - "proxy-api"
        - "-addr=:8086"
        - "-metrics-addr=:9996"
        - "-destination-addr=:8089"
        - "-telemetry-addr=:8087"
        - "-log-level=info"
      - name: tap
        ports:
        - name: grpc
          containerPort: 8088
        - name: admin-http
          containerPort: 9998
        image: gcr.io/runconduit/controller:dev-126be6ff-siggy
        imagePullPolicy: IfNotPresent
        args:
        - "tap"
        - "-addr=:8088"
        - "-metrics-addr=:9998"
        - "-log-level=info"
      - name: telemetry
        ports:
        - name: grpc
          containerPort: 8087
        - name: admin-http
          containerPort: 9997
        image: gcr.io/runconduit/controller:dev-126be6ff-siggy
        imagePullPolicy: IfNotPresent
        args:
        - "telemetry"
        - "-addr=:8087"
        - "-metrics-addr=:9997"
        - "-ignore-namespaces=kube-system"
        - "-prometheus-url=http://prometheus:9090"
        - "-log-level=info"
